# Generated by Django 3.1.3 on 2020-11-16 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
